name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore foosball-clash-upload.jks \
            -storepass "786cr007A@" \
            -keypass "786cr007A@" \
            -alias foosball \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Foosball Clash, OU=Mobile Games, O=Foosball Clash, L=Lahore, ST=Punjab, C=PK"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: foosball-clash-keystore
          path: foosball-clash-upload.jks
          retention-days: 1
